ktor:
  deployment:
    port: 8080
  application:
    modules:
      - org.sedaiadesigns.MonitoringKt.configureMonitoring
      - org.sedaiadesigns.SerializationKt.configureSerialization
      - org.sedaiadesigns.StatusPagesKt.configureStatusPages
      - org.sedaiadesigns.RoutingKt.configureRouting
  development: true
users:
  resource: "users.json"